"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "ar";

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<Language, Record<string, string>> = {
  en: {},
  ar: {
    "Egyptian Identity": "الهوية المصرية",
    "Educational Campus": "المجمع التعليمي",
    "Learn educational design, campus planning, BIM, sustainability and simulation before AI.": "تعلم التصميم التعليمي، وتخطيط المجمعات الدراسية، ونمذجة معلومات البناء، والاستدامة والمحاكاة قبل البدء بالذكاء الاصطناعي.",
    "Educational Vision": "الرؤية التعليمية",
    "Campus Master Planning": "المخطط العام للمجمع",
    "Academic Space Planning": "تخطيط المساحات الأكاديمية",
    "Student Flow Simulation": "محاكاة تدفق الطلاب",
    "Safety Planning": "تخطيط السلامة والأمان",
    "Smart Campus Operations": "تشغيل المجمع الذكي",
    "Defining academic programming, curriculum needs, enrollment goals, and spatial planning guidelines.": "تحديد البرنامج الأكاديمي، واحتياجات المناهج الدراسية، وأهداف الالتحاق، ومبادئ التخطيط الفراغي.",
    "Evaluating campus boundaries, zoning regulations, solar pathings, and surrounding terrain assets.": "تقييم حدود المجمع التعليمي، وأنظمة البناء، ومسارات الشمس، والمعالم التضاريسية المحيطة.",
    "Synthesizing building layouts, open plazas, landscape routes, and traffic interfaces.": "تطوير توزيعات المباني، والساحات المفتوحة، ومسارات تنسيق الموقع، وحركة النقل.",
    "Optimizing lecture halls, classrooms, laboratories, and study zones for high utilization.": "تحسين قاعات المحاضرات، والفصول الدراسية، والمختبرات، ومناطق الدراسة لتحقيق أعلى معدل إشغال.",
    "Simulating pedestrian patterns, class change traffic grids, and queue bottleneck zones.": "محاكاة حركة المشاة، ومسارات تغيير الفصول، ومناطق تكدس الطوابير.",
    "Modeling passive energy systems, daylight optimization, solar panels, and LCA footprints.": "نمذجة أنظمة الطاقة السلبية، وتحسين الإضاءة الطبيعية، والألواح الشمسية، وبصمات دورة الحياة.",
    "Simulating emergency fire evacuations, clear signage routing, and secure security boundaries.": "محاكاة الإخلاء في حالات الطوارئ والحرائق، ومسارات اللافتات، وتحديد الحرم الآمن.",
    "Linking actual campus IoT telemetry (room occupation, HVAC, lights) to a real-time virtual mesh.": "ربط مستشعرات إنترنت الأشياء للمجمع التعليمي (إشغال الغرف، التكييف، الإضاءة) بشبكة افتراضية فورية.",
    "Scheduling predictive building maintenance and class space schedules based on occupancy logs.": "جدولة أعمال صيانة المباني التنبؤية وجداول الفصول الدراسية بناءً على سجلات الإشغال.",
    "Geospatial digital twin framework mapping civil and building infrastructure.": "إطار عمل التوأم الرقمي الجغرافي لتخطيط البنية التحتية والمباني.",
    "Pedestrian simulation and crowd flow analysis modeling human behaviors.": "برنامج محاكاة المشاة وتحليل تدفق الحشود لنمذجة السلوك البشري.",
    "Building performance analysis integrating energy, heating, and cooling calculations.": "تحليل أداء المباني يدمج حسابات استهلاك الطاقة، والتدفئة، والتبريد.",
    "Urban Development": "التنمية الحضرية",
    "Start with urban planning principles, zoning, GIS and mobility planning before using AI for city-scale decision making.": "ابدأ بمبادئ التخطيط العمراني، وتصنيف المناطق، ونظم المعلومات الجغرافية وتخطيط التنقل قبل استخدام الذكاء الاصطناعي لاتخاذ القرارات على مستوى المدينة.",
    "Regional Analysis": "التحليل الإقليمي",
    "Land Use Planning": "تخطيط استخدامات الأراضي",
    "Mobility & Transportation": "التنقل والنقل",
    "Infrastructure Planning": "تخطيط البنية التحتية",
    "Public Realm": "الحيز العام والساحات",
    "Smart Growth Strategy": "استراتيجية النمو الذكي",
    "Evaluating regional economic data, environmental layouts, and spatial connections to contextualize development.": "تقييم البيانات الاقتصادية الإقليمية، والمخططات البيئية، والروابط المكانية لتحديد سياق التنمية.",
    "Optimizing zoning, land allocations, and density ratios to balance growth and community needs.": "تحسين اللوائح التنظيمية وتوزيع الأراضي ونسب الكثافة لتحقيق التوازن بين النمو واحتياجات المجتمع.",
    "Simulating vehicular transit, public transit routing, and pedestrian safety pathways.": "محاكاة حركة المركبات، ومسارات النقل العام، وممرات سلامة المشاة.",
    "Designing utility networks, stormwater management routes, and energy grid models.": "تصميم شبكات المرافق العامة، ومسارات تصريف السيول والأمطار، ونماذج شبكات الطاقة.",
    "Assessing heat island patterns, storm hazards, carbon offsets, and solar radiation profiles.": "تقييم أنماط الجزر الحرارية، ومخاطر العواصف، وخفض الانبعاثات الكربونية، ومستويات الإشعاع الشمسي.",
    "Drafting detailed block dimensions, heights, and parametric mass arrangements.": "صياغة أبعاد البلوكات التفصيلية، والارتفاعات، والتوزيعات الكتلية البارامترية.",
    "Optimizing public squares, streetscapes, parks, and accessibility zones for community engagement.": "تحسين الميادين العامة، ومخططات الشوارع، والحدائق، ومناطق الوصول لتعزيز المشاركة المجتمعية.",
    "Deploying generative parameters to establish long-term economic, ecological, and transit milestones.": "تطبيق المتغيرات التوليدية لتحديد الأهداف طويلة المدى للاقتصاد والبيئة والنقل.",
    "Procedural modeling software generating large-scale interactive 3D urban environments.": "برنامج النمذجة الإجرائية لتوليد بيئات حضرية ثلاثية الأبعاد تفاعلية واسعة النطاق.",
    "Open-source geographic information system software mapping and analyzing spatial data.": "برنامج نظم معلومات جغرافية مفتوح المصدر لرسم الخرائط وتحليل البيانات المكانية.",
    "Business intelligence dashboard analyzing municipal and demographic metrics.": "لوحة معلومات ذكاء الأعمال لتحليل المقاييس البلدية والديموغرافية.",
    "Smart City": "المدينة الذكية",
    "Commercial Tower": "البرج التجاري",
    "Healthcare": "الرعاية الصحية",
    "Hospitality": "الضيافة والمنتجعات",
    "Industrial": "المشاريع الصناعية",
    "Sustainable Community": "المجتمع المستدام",
    "CHOOSE YOUR MISSION": "اختر مهمتك",
    "Select a dynamic target node to initialize layout concepts.": "اختر العقدة المستهدفة لبدء عملية التصميم والتحسين.",
    "VIEW BRIEFING ➔": "عرض الملخص ➔",
    "NODE: ": "العقدة: ",
    "PROTOCOL ACTIVE": "البروتوكول نشط",
    "MISSION SPECS": "مواصفات المهمة",
    "WORKFLOW PIPELINE": "سلسلة سير العمل",
    "COGNITIVE AI TOOLS": "أدوات الذكاء الاصطناعي الإدراكية",
    "BEGINNER ADVISORY": "نصائح المبتدئين",
    "INITIALIZE PATHWAY": "بدء المسار",
    "DETAILED WORKFLOW PROTOCOLS": "بروتوكولات سير العمل المفصلة",
    "AI TOOLSETS & COGNITIVE STACK": "أدوات الذكاء الاصطناعي والحزم الإدراكية",
    "LEARNING ROADMAP & ACADEMIC PROTOCOL": "خارطة طريق التعلم والبروتوكول الأكاديمي",
    "BEGINNER DIRECTIVE": "توجيهات المبتدئين",
    "PHASE 01: PRINCIPLES": "المرحلة الأولى: المبادئ",
    "PHASE 02: BIM INTEGRATION": "المرحلة الثانية: تكامل نمذجة معلومات البناء (BIM)",
    "PHASE 03: COGNITIVE SYSTEM SYNCS": "المرحلة الثالثة: مزامنة الأنظمة الإدراكية",
    "Establish core domain knowledge (structural limits, healthcare standards, urban data models) manually without digital assists.": "تأسيس المعرفة الأساسية بالمجال (الحدود الإنشائية، معايير الرعاية الصحية، نماذج البيانات الحضرية) يدويًا دون مساعدة رقمية.",
    "Learn to translate manual concepts into coordinated BIM environments and database records.": "تعلم كيفية تحويل المفاهيم اليدوية إلى بيئات نمذجة معلومات بناء منسقة وسجلات قواعد بيانات.",
    "Connect parametric algorithms, ML models and generative models to optimize performance, carbon profiles, and aesthetics.": "ربط الخوارزميات البارامترية، ونماذج تعلم الآلة، والنماذج التوليدية لتحسين الأداء، وملفات الكربون، والجماليات الإنشائية.",
    "City Data": "بيانات المدينة",
    "GIS Analysis": "التحليل الجغرافي (GIS)",
    "Traffic Simulation": "محاكاة حركة المرور",
    "Population Prediction": "التنبؤ بالنمو السكاني",
    "Energy Analysis": "تحليل الطاقة",
    "Environmental Impact": "الأثر البيئي",
    "Infrastructure Optimization": "تحسين البنية التحتية",
    "AI Recommendations": "توصيات الذكاء الاصطناعي",
    "Site Analysis": "تحليل الموقع",
    "Building Massing": "الكتل البنائية",
    "Generative Design": "التصميم التوليدي",
    "Structural Analysis": "التحليل الإنشائي",
    "MEP Coordination": "تنسيق الأعمال الكهروميكانيكية (MEP)",
    "Energy Optimization": "تحسين استهلاك الطاقة",
    "Rendering": "الإخراج الفني والتجسيد",
    "Construction Documents": "مستندات التنفيذ والبناء",
    "Medical Program": "البرنامج الطبي",
    "Patient Flow": "حركة تدفق المرضى",
    "Emergency Routing": "توجيه مسارات الطوارئ",
    "Department Planning": "تخطيط الأقسام",
    "Operational Analysis": "التحليل التشغيلي",
    "Digital Twin": "التوأم الرقمي",
    "Facility Management": "إدارة المرافق",
    "Concept Design": "التصميم المفهومي",
    "Guest Experience": "تجربة الضيوف",
    "Landscape": "تنسيق الموقع والمسطحات الخضراء",
    "Operations": "العمليات والخدمات",
    "Marketing Visualization": "العروض التسويقية والمرئية",
    "Factory Layout": "مخطط المصنع",
    "Production Simulation": "محاكاة خطوط الإنتاج",
    "Logistics": "الخدمات اللوجستية",
    "Robot Optimization": "تحسين أداء الروبوتات",
    "Energy Monitoring": "مراقبة استهلاك الطاقة",
    "Predictive Maintenance": "الصيانة التنبؤية",
    "Climate Analysis": "التحليل المناخي",
    "Solar Analysis": "التحليل الشمسي",
    "Wind Simulation": "محاكاة الرياح",
    "Carbon Analysis": "تحليل الانبعاثات الكربونية",
    "Water Management": "إدارة مصادر المياه",
    "Smart Community": "المجتمع الذكي",
    "Learn GIS, urban planning, traffic simulation, sustainability, then apply AI.": "تعلم نظم المعلومات الجغرافية، والتخطيط الحضري، ومحاكاة المرور، والاستدامة، ثم قم بتطبيق الذكاء الاصطناعي.",
    "Master architecture fundamentals, BIM, structural systems and MEP before relying on AI.": "يجب إتقان أساسيات الهندسة المعمارية، ونمذجة معلومات البناء، والأنظمة الإنشائية والكهروميكانيكية قبل الاعتماد على الذكاء الاصطناعي.",
    "Study healthcare planning standards, circulation, medical equipment and safety, then optimize with AI.": "يجب دراسة معايير تخطيط المستشفيات، وحركة المرور، والمعدات الطبية والسلامة، ثم تحسينها باستخدام الذكاء الاصطناعي.",
    "Learn architecture, landscape, interiors and guest experience before using AI tools.": "يجب تعلم الهندسة المعمارية، وتنسيق الموقع، والتصاميم الداخلية وتجربة الضيوف قبل استخدام أدوات الذكاء الاصطناعي.",
    "Learn industrial engineering, lean manufacturing, automation and robotics before AI.": "يجب دراسة الهندسة الصناعية، والتصنيع الرشيق، والأتمتة والروبوتات قبل البدء بالذكاء الاصطناعي.",
    "Understand climate, passive design, energy, water and carbon analysis before AI optimization.": "يجب فهم المناخ، والتصميم السلبي، وتحليلات الطاقة والمياه والكربون قبل البدء في عمليات التحسين بالذكاء الاصطناعي.",
    "Ingesting real-time IoT feeds, municipal databases, and environmental sensors to construct a unified telemetry grid.": "تغذية تدفقات إنترنت الأشياء الفورية، وقواعد البيانات البلدية، والمستشعرات البيئية لبناء شبكة قياس موحدة.",
    "Mapping geography, contours, and physical features to build the baseline site boundary using ArcGIS AI datasets.": "رسم الخرائط الجغرافية، والكنتورية، والمعالم المادية لتحديد حدود الموقع الأساسية باستخدام مجموعات بيانات الذكاء الاصطناعي (ArcGIS).",
    "Analyzing pedestrian and automotive velocities (PTV Vissim/SUMO) to detect bottle-necks and layout issues.": "تحليل سرعات المشاة والسيارات (PTV Vissim/SUMO) للكشف عن الاختناقات ومشاكل المخططات الحضرية.",
    "Forecasting multi-decade community growth curves and demographic spatial densities using neural nets.": "التنبؤ بمنحنيات نمو المجتمع والكثافة السكانية الحضرية عبر عقود متعددة باستخدام الشبكات العصبية.",
    "Evaluating neighborhood heating and cooling loads along with microgrid electricity distribution metrics.": "تقييم أحمال التدفئة والتبريد في الأحياء السكنية ومقاييس توزيع الكهرباء عبر الشبكات الصغيرة.",
    "Running local heat island, wind tunnel, and carbon footprint predictions over the conceptual layouts.": "تشغيل محاكاة الجزر الحرارية المحلية، ونفق الرياح، وتوقعات البصمة الكربونية على المخططات المقترحة.",
    "Using genetic algorithms to optimize water routing, utility hubs, and waste management nodes.": "استخدام الخوارزميات الجينية لتحسين مسارات المياه، ومراكز الخدمات، وعقد إدارة النفايات.",
    "Leveraging deep learning to propose design changes maximizing comfort, transit, and sustainability.": "الاستفادة من التعلم العميق لاقتراح تغييرات في التصميم تحقق أقصى درجات الراحة والتنقل والاستدامة.",
    "Evaluating zoning regulations, solar pathings, and surrounding tower heights to optimize mass potential.": "تقييم قوانين البناء، ومسارات الشمس، وارتفاعات الأبراج المجاورة لتحقيق أقصى استفادة من كتلة البرج.",
    "Synthesizing early structural shapes to maximize rentable area and structural wind dynamics.": "تطوير أشكال هيكلية أولية لزيادة المساحات التأجيرية وتحسين مقاومة الرياح.",
    "Iterating thousands of layout configurations based on parametric floorplans, heights, and orientations.": "توليد آلاف التكوينات التصميمية بناءً على مخططات الطوابق البارامترية، والارتفاعات، والاتجاهات.",
    "Testing load paths, seismic shear walls, and core placements through automated finite element checks.": "اختبار مسارات الأحمال، وجدران القص الزلزالية، وتوزيعات قلوب المباني عبر اختبارات العناصر المحدودة المؤتمتة.",
    "AI clash detection modeling ventilation ducts, electrical cable trays, and plumbing networks inside Revit.": "كشف التعارضات بالذكاء الاصطناعي لشبكات التهوية، ومسارات الكابلات الكهربائية، وشبكات السباكة داخل ريفيت.",
    "Simulating high-performance facades, solar shading angles, and thermal envelope requirements.": "محاكاة الواجهات عالية الأداء، وزوايا التظليل الشمسي، ومتطلبات الغلاف الحراري للمبنى.",
    "Converting building wireframes into photorealistic immersive materials and lights using AI render pipelines.": "تحويل الهياكل السلكية للمباني إلى مواد وإضاءات واقعية غامرة باستخدام خطوط الإخراج الفني بالذكاء الاصطناعي.",
    "Extracting automated quantity take-offs, detail drawing sheets, and schedule sheets directly from BIM data.": "استخراج جداول الكميات، ولوحات التفاصيل الرسومات، ولوحات الجداول الزمنية مؤتمتة من بيانات نمذجة معلومات البناء.",
    "Defining detailed clinical programs, patient categories, and departmental area allocations.": "تحديد البرامج السريرية المفصلة، وفئات المرضى، وتوزيع مساحات الأقسام المختلفة.",
    "Running agent-based model paths to trace patient and staff steps, reducing walk times and waiting states.": "تشغيل محاكاة تتبع خطوات المرضى والكادر الطبي لتقليل أوقات المشي والانتظار.",
    "Simulating high-stress ambulance arrivals, triage flow, and trauma unit routes to minimize response times.": "محاكاة وصول سيارات الإسعاف، وتدفق الفرز الطبي، ومسارات وحدة الطوارئ لتقليل وقت الاستجابة.",
    "Optimizing proximity relationships between surgeries, ICU, imaging, and inpatient wards.": "تحسين علاقات الجوار والمسافات بين غرف العمليات، والعناية المركزة، والأشعة، وأجنحة التنويم.",
    "Predicting hospital bed utilization, staffing schedules, and medical material logistics flows.": "التنبؤ بمعدلات إشغال الأسرة، وجداول الموظفين، والخدمات اللوجستية للمستلزمات الطبية.",
    "Maintaining critical negative pressure, sterile air flows, and intensive lighting loads efficiently.": "الحفاظ على الضغط السلبي الحرج، وتدفقات الهواء المعقم، وأحمال الإضاءة المكثفة بكفاءة عالية.",
    "Linking IoT sensor telemetry (temperature, equipment location, bed states) into a real-time hospital mesh.": "ربط بيانات مستشعرات إنترنت الأشياء (درجة الحرارة، مواقع الأجهزة، حالات الأسرة) بشبكة المستشفى الفورية.",
    "Scheduling predictive medical machinery calibrations and space sanitizations based on occupancy streams.": "جدولة معايرة الأجهزة الطبية التنبؤية وعمليات تعقيم المساحات بناءً على تدفقات الإشغال.",
    "Mapping shoreline views, solar orientations, acoustic pathways, and natural topography assets.": "رسم مسارات الرؤية الشاطئية، والاتجاهات الشمسية، والمسارات الصوتية، والمعالم التضاريسية الطبيعية للموقع.",
    "Synthesizing local cultural motifs and organic geometry forms into premium resort layouts.": "دمج الزخارف الثقافية المحلية والأشكال الهندسية العضوية في مخططات المنتجعات الراقية.",
    "Optimizing spatial transitions from lobby to villas, ensuring premium privacy and fluid circulations.": "تحسين الانتقالات الفراغية من البهو إلى الفلل، لضمان أعلى مستويات الخصوصية والمرونة في الحركة.",
    "Designing exterior pools, green hills, and pathways matching native ecosystem microclimates.": "تصميم المسابح الخارجية، والتلال الخضراء، والممرات لتتوافق مع المناخات الدقيقة للنظام البيئي المحلي.",
    "Coordinating natural cross-ventilations, solar water heaters, and smart room occupancy switches.": "تنسيق التهوية الطبيعية المتقاطعة، وسخانات المياه الشمسية، ومفاتيح الغرف الذكية المرتبطة بالإشغال.",
    "Optimizing backend service tunnels, laundry routing, and kitchen-to-guest circulation vectors.": "تحسين أنفاق الخدمات الخلفية، ومسارات الغسيل، وخطوط الخدمة من المطبخ إلى غرف الضيوف.",
    "Generating cinematic luxury rendering materials and walk-throughs to showcase the guest experience.": "إنتاج لقطات سينمائية ومواد إخراج وجولات افتراضية فاخرة لعرض تجربة الضيافة المتكاملة.",
    "Optimizing production line machinery layout to minimize material transfer times.": "تحسين توزيع معدات خطوط الإنتاج لتقليل أوقات نقل المواد الخام والمنتجات.",
    "Simulating manufacturing cycles and bottleneck states under varying supply loads.": "محاكاة دورات التصنيع وحالات الاختناق تحت أعباء وكميات الإمداد المتغيرة.",
    "Coordinating autonomous automated guided vehicles (AGVs) and warehouse storage layouts.": "تنسيق المركبات الموجهة تلقائيًا ذاتية القيادة (AGVs) ومخططات التخزين في المستودعات.",
    "Programming robot arm paths to maximize mechanical safety and cycles per hour.": "برمجة مسارات الأذرع الروبوتية لتحقيق أقصى درجات الأمان الميكانيكي وزيادة عدد الدورات في الساعة.",
    "Tracking massive assembly line motors, high-heat furnaces, and central HVAC load curves.": "مراقبة محركات خطوط التجميع الضخمة، والأفران عالية الحرارة، ومنحنيات أحمال التكييف المركزي.",
    "Detecting early mechanical vibration variations to schedule repairs before failure.": "الكشف عن التغيرات المبكرة في الاهتزازات الميكانيكية لجدولة عمليات الإصلاح قبل حدوث الأعطال.",
    "Generating live unified factory floor wireframes syncing actual production velocities.": "توليد هياكل سلكية حية وموحدة لأرضية المصنع تتزامن مع سرعات الإنتاج الفعلية.",
    "Ingesting historical wind, humidity, and sun tracking profiles to define passive solar design angles.": "استيراد بيانات الرياح، والرطوبة، ومسارات الشمس التاريخية لتحديد زوايا التصميم الشمسي السلبي.",
    "Mapping photovoltaic potential, building shadows, and solar heat radiation values.": "رسم خرائط إمكانات الطاقة الكهروضوئية، وظلال المباني، وقيم الإشعاع الحراري الشمسي.",
    "Evaluating pedestrian wind comfort and building airflow velocities using digital wind tunnels.": "تقييم راحة المشاة من الرياح وسرعات تدفق الهواء في المباني باستخدام أنفاق رياح رقمية.",
    "Performing automated life cycle assessments (LCA) to compute total embodied carbon values.": "إجراء تقييمات آلية لدورة الحياة (LCA) لحساب إجمالي قيم الكربون المتضمن.",
    "Sizing bioswales, rainwater harvesters, greywater recycling loops, and flood path basins.": "تحديد أحجام قنوات التصفية الحيوية، وحصادات مياه الأمطار، وحلقات تدوير المياه الرمادية، وأحواض السيول.",
    "Integrating geothermal heating, passive solar designs, and smart microgrids.": "دمج التدفئة الجوفية الأرضية، والتصاميم الشمسية السلبية، والشبكات الكهربائية الصغيرة الذكية.",
    "Establishing community-level sharing metrics for energy, electric transit, and urban farming.": "وضع معايير مشاركة الطاقة، والنقل الكهربائي، والزراعة الحضرية على مستوى المجتمع المحلي.",
    "AI-driven GIS platform mapping municipal layouts and large-scale topography.": "منصة نظم معلومات جغرافية معززة بالذكاء الاصطناعي لتخطيط البلديات والتضاريس واسعة النطاق.",
    "Open-source geospatial processing with machine learning terrain classification.": "معالجة البيانات الجغرافية المكانية مفتوحة المصدر مع تصنيف التضاريس بتعلم الآلة.",
    "Cloud computation for satellite imaging and regional environmental analysis.": "الحوسبة السحابية لتحليل صور الأقمار الصناعية والتحليلات البيئية الإقليمية.",
    "Advanced traffic planning simulator modeling agent-based vehicle flows.": "برنامج محاكاة متطور لتخطيط حركة المرور ينمذج تدفقات المركبات بشكل مستقل.",
    "Simulation of Urban MObility modeling microscopic traffic networks.": "محاكاة التنقل الحضري عبر نمذجة شبكات حركة المرور المجهرية.",
    "Generative cloud BIM scoring solar, wind, noise, and microclimate variables.": "نمذجة معلومات البناء السحابي التوليدية لتقييم متغيرات الشمس والرياح والضوضاء والمناخ الدقيق.",
    "Parametric layout generator optimization for floorplans and mass designs.": "مولد مساحات بارامتري لتحسين وتصميم مخططات الطوابق والكتل البنائية.",
    "Large language model analyzing regulatory scripts, briefs, and documentation.": "نموذج لغوي كبير لتحليل المستندات التنظيمية والملخصات والوثائق الفنية.",
    "Advanced reasoning model writing complex structural scripts and parameters.": "نموذج استدلال متقدم لكتابة البرامج النصية والمتغيرات الإنشائية المعقدة.",
    "Localized database assistant matching project requirements to structural codes.": "مساعد قاعدة بيانات محلي يطابق متطلبات المشروع مع الأكواد الإنشائية.",
    "Cinematic visual telemetry rendering cities and buildings in real-time.": "تجسيد سينمائي فوري للمدن والمباني باستخدام القياسات البعادية.",
    "Real-time immersive visualization syncing high-fidelity asset animations.": "تجسيد غامر فوري يزامن لقطات وحركات الأصول والكتل الإنشائية بدقة عالية.",
    "3D geospatial rendering engine streaming planetary terrain tiles.": "محرك تجسيد جغرافي ثلاثي الأبعاد يبث تضاريس الكوكب.",
    "Generative parametric drafting automating structural components.": "صياغة بارامترية توليدية تؤتمت المكونات الإنشائية.",
    "AI-accelerated raytracing engine rendering photorealistic building scenes.": "محرك تتبع الأشعة معزز بالذكاء الاصطناعي لتجسيد مشاهد مباني واقعية تمامًا.",
    "Landscape and architecture rendering engine emphasizing foliage and atmosphere.": "محرك تجسيد المناظر الطبيعية والمعمارية يركز على النباتات والغلاف الجوي.",
    "Image generator producing conceptual materials and aesthetic inspiration.": "مولد صور ينتج مواد مفهومية وإلهامًا جماليًا.",
    "Generative texture and graphic tool for building surfaces.": "أداة رسومية وتوليدية لتصميم أسطح وخامات المباني.",
    "Unified construction platform tracking MEP submittals and issues.": "منصة بناء موحدة تتبع وثائق وطلبات الكهروميكانيك والأعمال الإنشائية.",
    "Multimethod simulation modeling hospital workflows and logistics.": "محاكاة متعددة الطرق لتخطيط وتصميم سير العمليات والخدمات اللوجستية في المستشفيات.",
    "IoT integration platform linking physical buildings to database twins.": "منصة دمج لإنترنت الأشياء تربط المباني المادية بتوائم قواعد البيانات الفورية.",
    "Real-time computer vision identifying safety gear and tracking site footfalls.": "رؤية حاسوبية فورية تحدد معدات الأمان وتتتبع خطوات الحركة في الموقع.",
    "Parametric modeling studio generating complex curvilinear shapes.": "استوديو نمذجة بارامترية لتوليد وتصميم أشكال منحنية معقدة.",
    "Industrial engineering platform simulation digital production.": "منصة هندسة صناعية لمحاكاة خطوط الإنتاج والعمليات الرقمية.",
    "3D simulation engine modeling warehouse layouts and logistics.": "محرك محاكاة ثلاثي الأبعاد ينمذج مخططات المستودعات والخدمات اللوجستية.",
    "Robot simulation platform training autonomous vehicles and arms.": "منصة محاكاة وتدريب الروبوتات لبرمجة الأذرع والمركبات ذاتية القيادة.",
    "Real-time virtual collaboration space syncing multiple 3D files.": "مساحة تعاون افتراضية فورية تضمن مزامنة ملفات التصاميم ثلاثية الأبعاد المتعددة.",
    "Building performance analysis tracking solar, daylight, and energy usage.": "تحليل أداء المباني لتتبع الإشراق الشمسي والإضاءة النهارية واستهلاك الطاقة.",
    "Automated carbon calculator measuring total embodied building emissions.": "حاسبة كربون مؤتمتة تقيس إجمالي الانبعاثات الكربونية المتضمنة في المبنى.",
    "Rhino/Grasshopper plugins simulating environmental solar, wind, and radiation.": "إضافات لبرنامجي راينو وجراسهوبر تحاكي العوامل البيئية من شمس ورياح وإشعاع.",
    "Construction and Project Management for the New Damietta Governorate administrative headquarters building, overlooking the Nile River, covering approximately 15,000 m².": "إدارة المشروعات والإشراف على التنفيذ لمبنى ديوان عام محافظة دمياط الجديد المطل على نهر النيل بمساحة تقارب 15,000 متر مربع.",
    "CUBE Consultants provided comprehensive Project Management and Construction Supervision services for the Damietta Governorate building. Scope of work included planning and scheduling of construction phases, technical supervision for the integration of architectural, structural, and MEP engineering trades, commercial management (Q.S. reviews, payment certificate approvals), and on-site construction safety and quality control audits.": "قدمت كيو ب للاستشارات خدمات إدارة المشاريع والإشراف على التنفيذ المتكاملة لمبنى ديوان عام محافظة دمياط الجديد. وشمل نطاق العمل تخطيط وجدولة مراحل البناء، والإشراف الفني للتنسيق بين التخصصات المعمارية والإنشائية والكهروميكانيكية (MEP)، بالإضافة إلى الإدارة التجارية والمراجعة المالية وإجراءات ضبط الجودة والسلامة في الموقع.",
    "Project Management and Construction Supervision of the smart, sustainable Sahara International School campus in the New Administrative Capital.": "إدارة المشروعات والإشراف على التنفيذ لمجمع مدرسة الصحراء الدولية الذكي والمستدام بالعاصمة الإدارية الجديدة.",
    "CUBE Consultants acted as the Project Management partner for the Sahara International School. Services included complete planning and scheduling coordination, resource allocation tracking, document control, and on-site technical supervision. The project features flexible, technology-driven spaces and a colorful facade engineered to optimize natural sunlight and ventilation.": "عملت كيو ب للاستشارات كشريك لإدارة مشروع مدرسة الصحراء الدولية بالعاصمة الإدارية الجديدة. وشملت الخدمات التنسيق الكامل للجدولة والتخطيط، ومتابعة توزيع الموارد، والتحكم في المستندات، والإشراف الفني الموقعي للمبنى التعليمي الذكي والمستدام.",
    "Construction Management and value engineering for the Kemet Tower administrative development in the New Administrative Capital.": "إدارة التنفيذ وهندسة القيمة لمشروع برج كيميت الإداري بالعاصمة الإدارية الجديدة.",
    "CUBE Consultants oversaw the construction management, schedule tracking, and commercial management for the Kemet Tower. Key services delivered: structural submittal review, MEP trade coordination support, value engineering, and change management protocols to ensure project delivery within scope and budget.": "أشرفت كيو ب للاستشارات على إدارة التنفيذ ومتابعة الجدول الزمني والإدارة التجارية لبرج كيميت الإداري بالعاصمة الإدارية الجديدة. شملت الخدمات مراجعة المخططات الإنشائية وتنسيق الأنظمة الكهروميكانيكية وهندسة القيمة وإجراءات إدارة التغيير لضمان تسليم المشروع.",
    "A premium master-planned development by CUBE Consultants, integrating mixed-use commercial and residential districts.": "مخطط رئيسي متميز من كيو ب للاستشارات، يدمج المناطق التجارية والسكنية متعددة الاستخدامات.",
    "Designed as an urban intelligence hub, the Madar development integrates residential spaces, boutique offices, green recreational paths, and smart infrastructure components.": "صُمم مشروع مدار كمركز حضري ذكي يدمج المساحات السكنية، والمكاتب المتميزة، والمسارات الترفيهية الخضراء، ومكونات البنية التحتية الذكية.",
    "Project Management, design coordination, and commercial oversight of the mixed-use Madar development.": "إدارة المشاريع والتنسيق التصميمي والإشراف التجاري لمشروع مدار متعدد الاستخدامات.",
    "CUBE Consultants provided design management, planning, and schedule tracking for the Madar masterplan. Services included contract negotiations with stakeholders, planning engineering, budget oversight, and technical supervision of early conceptual layouts.": "قدمت كيو ب للاستشارات إدارة التصميم والتخطيط ومتابعة الجدول الزمني لمخطط مدار الرئيسي. وشملت الخدمات إدارة العقود والمفاوضات، وتخطيط هندسة الموارد، والإشراف الفني للتخطيطات المبدئية.",
    "Site supervision and construction scheduling for the Zomra East residential community.": "الإشراف الموقعي وجدولة التنفيذ لمشروع زمرة إيست السكني.",
    "CUBE Consultants delivered site supervision, document control, and schedule updates for the Zomra East compound. Responsibilities included quality control checks for concrete structures, structural alignment audits, and trade coordination across architectural and landscaping works.": "قدمت كيو ب للاستشارات خدمات الإشراف الموقعي، والتحكم في المستندات، وتحديثات الجدول الزمني لكمبوند زمرة إيست السكني، لضمان أعلى مستويات الجودة الإنشائية والتنسيق للموقع العام.",
    "Project Management and Technical Supervision for the Boardwalk Residence compound in the R7 zone.": "إدارة المشروعات والإشراف الفني لكمبوند بوردووك السكني بمنطقة R7 بالعاصمة الإدارية الجديدة.",
    "CUBE Consultants directed project planning, risk management, and on-site supervision for the Boardwalk residential development. Services included schedule maintenance, submittal approvals, safety regulation audits, and coordination with El Asreya Developments' contracting partners.": "أدارت كيو ب للاستشارات تخطيط المشروع، وإدارة المخاطر، والإشراف الموقعي لمشروع بوردووك السكني في منطقة R7 بالعاصمة الإدارية الجديدة، بالتنسيق مع شركاء التنفيذ.",
    "Technical supervision and scheduling coordination for the Mada Residence development.": "الإشراف الفني وتنسيق الجداول الزمنية لمشروع سكن مدى.",
    "CUBE Consultants managed overseas coordination, scheduling reviews, and technical submittal approvals for the Mada Residence. Tasks included project planning milestones audit, quality control tracking, and document control synchronization between design and construction teams.": "أدارت كيو ب للاستشارات التنسيق الخارجي ومراجعة الجداول الزمنية واعتماد التقديمات الفنية لسكن مدى بسلطنة عمان، لضمان تطابق أعمال التنفيذ مع المعايير.",
    "Mega-project planning and risk management coordination for the SKIV industrial village under Saudi Vision 2030.": "تخطيط المشاريع الكبرى وتنسيق إدارة المخاطر للقرية الصناعية السعودية الكورية (SKIV) ضمن رؤية 2030.",
    "CUBE Consultants provided mega-project planning, planning engineering, resource allocation modeling, and risk mitigation management for SKIV Jazan. Responsibilities included scheduling complex production line structures, trade coordination for infrastructure lines, and stakeholder communication pathways.": "قدمت كيو ب للاستشارات خدمات التخطيط للمشروعات الكبرى، وهندسة التخطيط، ونمذجة تخصيص الموارد، وإدارة المخاطر لمشروع القرية الصناعية السعودية الكورية بجازان، لربط خطوط الإنتاج والخدمات اللوجستية.",

    // Navigation
    "HOME": "الرئيسية",
    "ABOUT": "من نحن",
    "PROJECTS": "المشاريع",
    "SERVICES": "الخدمات",
    "INSIGHTS": "الأخبار والرؤى",
    "CONTACT US": "اتصل بنا",
    "Art Gallery": "معرض الفنون",

    // About Page (Grid Design)
    "Identity Framework": "إطار الهوية",
    "Leadership": "القيادة",
    "Founder & CEO": "المؤسس والرئيس التنفيذي",
    "Dr. Ashraf Abdel Mohsen": "أ.د. أشرف عبد المحسن",
    "In 1990, Professor Dr. Ashraf Abdel Mohsen founded CUBE, an architecture firm with a specialized focus. Driven by his passion for the field, he carefully selected a team of skilled designers and creatives to collaborate closely on projects, bringing unique visions to fruition. Abdel Mohsen’s goal was to promote sustainable urban expansion that adhered to international standards. He proposed a visionary plan named Cairo 2050 to enhance the urban quality of Cairo, which spanned from 2005 to 2010.": "في عام 1990، أسس الأستاذ الدكتور أشرف عبد المحسن شركة كيو ب (CUBE)، وهي شركة هندسة معمارية ذات تركيز متخصص. وبدافع من شغفه بهذا المجال، اختار بعناية فريقاً من المصممين والمبدعين المهرة للتعاون عن كثب في المشاريع، وتحقيق رؤى فريدة على أرض الواقع. كان هدف عبد المحسن هو تعزيز التوسع الحضري المستدام الذي يلتزم بالمعايير الدولية. وقد اقترح خطة رؤيوية تسمى القاهرة 2050 لتحسين الجودة الحضرية للقاهرة، والتي امتدت من عام 2005 إلى عام 2010.",
    "1. SPIRIT CARE": "١. رعاية الروح",
    "Design that nurtures the human soul by prioritizing emotional experience, peace, balance, and meaning.": "تصميم يغذي الروح الإنسانية من خلال إعطاء الأولوية للتجربة العاطفية والسلام والتوازن والمعنى.",
    "Outcome:": "النتيجة:",
    "Spaces that heal, inspire, and connect": "مساحات تشفي، تلهم، وتربط",
    "2. EARTH CARE": "٢. رعاية الأرض",
    "Environmental responsibility as a core principle. True sustainability that coexists with nature rather than consuming it.": "المسؤولية البيئية كمبدأ أساسي. استدامة حقيقية تتعايش مع الطبيعة بدلاً من استهلاكها.",
    "Projects that coexist with nature rather than consume it": "مشاريع تتعايش مع الطبيعة بدلاً من استهلاكها",
    "3. SCIENCE & TECHNOLOGY": "٣. العلم والتكنولوجيا",
    "Integrating AI and smart systems to enhance performance, efficiency, and user experience to drive continuous innovation.": "دمج الذكاء الاصطناعي والأنظمة الذكية لتعزيز الأداء والكفاءة وتجربة المستخدم لقيادة الابتكار المستمر.",
    "Intelligent, future-ready environments": "بيئات ذكية وجاهزة للمستقبل",
    "What We Do": "ماذا نعمل",
    "Our Divisions": "أقسامنا",
    "City & Country Visions": "رؤى المدن والدول",
    "Architecture & Urban Design": "العمارة والتصميم العمراني",
    "Technical Consultancy": "الاستشارات الفنية",
    "Project Management": "إدارة المشاريع",
    "Development Advisory": "الاستشارات التطويرية",
    "Environment & Sustainability": "البيئة والاستدامة",
    "Interior Design": "التصميم الداخلي",
    "2026 Philosophy": "فلسفة ٢٠٢٦",
    "Spirit Care": "رعاية الروح",
    "1. SOUL": "١. الروح",
    "Every space must feel alive through light, shadow, and proportion.": "يجب أن تبدو كل مساحة حية من خلال الضوء والظل والتناسب.",
    "2. SUN": "٢. الشمس",
    "Light is the primary generator of life, dictating solar orientation and shading.": "الضوء هو المولد الأساسي للحياة، ويملي التوجيه الشمسي والتظليل.",
    "3. AIR": "٣. الهواء",
    "Creating movement and comfort through natural cross-ventilation.": "خلق الحركة والراحة من خلال التهوية الطبيعية المتقاطعة.",
    "4. WATER": "٤. الماء",
    "A natural cooling agent that offers visual and spiritual reflection.": "عامل تبريد طبيعي يوفر انعكاساً بصرياً وروحياً.",
    "5. EARTH": "٥. الأرض",
    "Sustainability rooted deeply in context and local, natural materials.": "الاستدامة المتجذرة بعمق في السياق والمواد الطبيعية المحلية.",
    "SOUL": "الروح",
    "SUN": "الشمس",
    "AIR": "الهواء",
    "WATER": "الماء",
    "EARTH": "الأرض",
    "Palestine": "فلسطين",
    "Iraq": "العراق",
    "Libya": "ليبيا",
    "South Africa": "جنوب أفريقيا",
    "Netherland": "هولندا",
    "Finland": "فنلندا",
    "Russia": "روسيا",
    "South Korea": "كوريا الجنوبية",
    "Vietnam": "فيتنام",

    // Hero Carousel
    "CUBE CONSULTANTS": "كيو ب للاستشارات",
    "35 Years of Achievements": "35 عاماً من الإنجازات",
    "Founded in 1990. Constructing ecosystems of ambition. Melding Science, Technology & Architecture.": "تأسست عام 1990. بناء نظم طموحة. دمج العلم والتكنولوجيا والهندسة المعمارية.",
    "Kemet Tower": "برج كيميت",
    "An iconic modern commercial development integrating advanced building systems and structural mastery.": "تطوير تجاري حديث مبدع يدمج أنظمة البناء المتقدمة والبراعة الإنشائية.",
    "Red Hills Resort": "منتجع التلال الحمراء",
    "An exclusive resort-style masterplan on the Red Sea coast, merging sloped structural orientation with seaside beauty.": "مخطط رئيسي حصري على طراز المنتجعات على ساحل البحر الأحمر، يدمج التوجه الهيكلي المائل مع جمال شاطئ البحر.",
    "Saudi Korean Industrial Village": "القرية الصناعية السعودية الكورية",
    "A world-class industrial cluster under Saudi Vision 2030, establishing an integrated primary production and logistics zone.": "مجمع صناعي عالمي المستوى ضمن رؤية السعودية 2030، يهدف لإنشاء منطقة إنتاج أولية ولوجستية متكاملة.",
    "Mada Residence": "سكن مدى",
    "A luxury coastal residential community in Oman, matching high-end modern materials with local context and environment.": "مجتمع سكن ساحلي فاخر في عمان، يطابق المواد الحديثة الراقية مع السياق والبيئة المحلية.",
    "VIEW PROJECT": "عرض المشروع",
    "ARCHITECTURE / URBANISM / DIGITAL INNOVATION": "الهندسة المعمارية / التخطيط العمراني / الابتكار الرقمي",
    "35 years of achievements": "35 عاماً من الإنجازات",
    "Founded in 1990": "تأسست في عام 1990",
    "PROJECTS_STAT": "مشروع",
    "YEARS": "سنة",
    "COUNTRIES": "دول",
    "EXPERTS": "خبراء",

    // About Us
    "ABOUT US": "من نحن",
    "Designing spaces \nthat inspire life.": "تصميم مساحات \nتلهم الحياة.",
    "Designing spaces that inspire life.": "تصميم مساحات تلهم الحياة.",
    "CUBE CONSULTANTS is a multidisciplinary architecture and design practice established in 1990.": "كيو ب للاستشارات هي ممارسة هندسة معمارية وتصميم متعددة التخصصات تأسست عام 1990.",
    "For over 35 years, we have delivered innovative solutions that connect people, places and ideas.": "لأكثر من 35 عاماً، قدمنا حلولاً مبتكرة تربط بين الناس والأماكن والأفكار.",
    "LEARN MORE": "اقرأ المزيد",

    // Services
    "OUR SERVICES": "خدماتنا",
    "Identity-driven and buildable masterplanning, commercial, and residential projects.": "مخططات رئيسية ومشاريع تجارية وسكنية مدفوعة بالهوية وقابلة للبناء.",
    "Engineering & Consultancy": "الهندسة والاستشارات",
    "Precision coordination, value engineering, and structural design optimization.": "التنسيق الدقيق وقيمة الهندسة وتحسين التصميم الإنشائي.",
    "Rigorous construction scheduling, budget management, and site quality control.": "جداول بناء صارمة، وإدارة الميزانية، ومراقبة جودة الموقع.",
    "Macro-level identity frameworks and development masterplans for cities and nations.": "أطر هوية على المستوى الكلي ومخططات تنمية للمدن والدول.",
    "Feasibility studies, market analysis, and land use optimization assessments.": "دراسات الجدوى، تحليل السوق، وتقييمات تحسين استخدام الأراضي.",
    "Sustainability": "الاستدامة",
    "Carbon-conscious passive architecture, smart water systems, and solar orientation.": "عمارة سلبية واعية بالكربون، وأنظمة مياه ذكية، وتوجيه شمسي.",
    "Human-centered indoor spaces optimizing lighting, acoustic flow, and premium materiality.": "مساحات داخلية تتمحور حول الإنسان لتحسين الإضاءة والتدفق الصوتي والمواد الممتازة.",

    // Selected Projects & News
    "SELECTED PROJECTS": "مشاريع مختارة",
    "VIEW ALL PROJECTS": "عرض جميع المشاريع",
    "LATEST INSIGHTS": "أحدث الأخبار والرؤى",
    "VIEW ALL INSIGHTS": "عرض جميع الأخبار والرؤى",
    "READ MORE": "اقرأ المزيد",
    "NEWS & INSIGHTS": "الأخبار والرؤى",

    // Footer
    "ARCHITECTURE. URBANISM. DIGITAL INNOVATION": "الهندسة المعمارية. التخطيط العمراني. الابتكار الرقمي",
    "CUBE was founded in 1990, by Prof. Ashraf Abdel Mohsen, professor of architecture at the Faculty of Engineering, Ain Shams University ,Cairo, Egypt.": "تأسست كيو ب عام 1990 على يد أ.د. أشرف عبد المحسن، أستاذ العمارة بكلية الهندسة، جامعة عين شمس، القاهرة، مصر.",
    "6 Somal Street, Korba, Cairo, Egypt": "6 شارع الصومال، الكوربة، القاهرة، مصر",
    "CUBE@CUBECONSULTANTS.ORG": "CUBE@CUBECONSULTANTS.ORG",
    "(+2) 02 2417 9168 / 02 2690 0673": "0673 2690 02 / 9168 2417 02 (2+)",
    "© 2026 CUBE CONSULTANTS. ALL RIGHTS RESERVED.": "© 2026 كيو ب للاستشارات. جميع الحقوق محفوظة.",
    "PRIVACY POLICY": "سياسة الخصوصية",
    "TERMS & CONDITIONS": "الشروط والأحكام",
    "OUR TEAM": "فريقنا",
    "CAREERS": "الوظائف",
    "NEWS & INSIGHTS_FOOTER": "الأخبار والرؤى",
    "CONTACT": "اتصل بنا",

    // Contact Page
    "Get in Touch": "تواصل معنا",
    "Our Profile": "ملفنا التعريفي",
    "CUBE was founded in 1990 by Prof. Ashraf Abdel Mohsen, professor of architecture at the Faculty of Engineering, Ain Shams University, Cairo, Egypt. Over 35 years, we have crafted regional blueprints, commercial landmarks, and communities with architectural mastery.": "تأسست كيو ب عام 1990 على يد أ.د. أشرف عبد المحسن، أستاذ العمارة بكلية الهندسة، جامعة عين شمس، القاهرة، مصر. على مدار 35 عاماً، قمنا بصياغة مخططات إقليمية ومعالم تجارية ومجتمعات ببراعة معمارية.",
    "Cairo Headquarters": "المقر الرئيسي بالقاهرة",
    "ADDRESS": "العنوان",
    "TELEPHONE": "التليفون",
    "EMAIL": "البريد الإلكتروني",
    "Send Us a Message": "أرسل لنا رسالة",
    "Your Name": "الاسم",
    "Your Email": "البريد الإلكتروني",
    "Subject": "الموضوع",
    "Message": "الرسالة",
    "Write your message here...": "اكتب رسالتك هنا...",
    "SEND MESSAGE": "إرسال الرسالة",
    "SENDING...": "جاري الإرسال...",
    "Thank you!": "شكراً لك!",
    "Your message has been sent successfully. We will get back to you shortly.": "تم إرسال رسالتك بنجاح. وسنعاود الاتصال بك قريباً.",
    "SEND ANOTHER MESSAGE": "أرسل رسالة أخرى",
    "BOOK_APPOINTMENT": "احجز موعدًا",

    // Projects Page
    "Our Portfolio": "معرض أعمالنا",
    "Our Works": "أعمالنا",
    "Portfolio": "معرض الأعمال",
    "PORTFOLIO": "معرض الأعمال",
    "Projects": "المشاريع",
    "Movies": "الأفلام",
    "Visions & Masterplans": "الرؤى والمخططات العامة",
    "Sector": "القطاع",
    "Region": "المنطقة",
    "Keywords": "الكلمات المفتاحية",
    "Search by keywords or description (e.g., 'central landscape')...": "ابحث بالكلمات أو الوصف (مثال: 'مسطحات خضراء مركزية')...",
    "Clear Filters": "مسح التصفية",
    "No projects match your search criteria.": "لا توجد مشاريع تطابق معايير البحث الخاصة بك.",
    "No movies match your search criteria.": "لا توجد أفلام تطابق معايير البحث الخاصة بك.",

    // Sectors
    "All": "الكل",
    "Residential & Resorts": "السكني والمنتجعات",
    "Industrial & Infrastructure": "الصناعي والبنية التحتية",
    "Towers & Offices": "الأبراج والمكاتب",
    "Commercial & Retail": "التجاري والتجزئة",
    "Tourism & Mixed-Use": "السياحي والمتعدد الاستخدامات",
    "Mixed-Use & Visions": "متعدد الاستخدامات والرؤى",
    "Culture & Education": "الثقافة والتعليم",
    "Public Buildings & Retail": "المباني العامة والتجزئة",
    "Urban Planning": "التخطيط العمراني",
    "All Sectors": "جميع القطاعات",

    // Regions
    "All Regions": "جميع المناطق",
    "Egypt": "مصر",
    "KSA": "المملكة العربية السعودية",
    "UAE": "الإمارات العربية المتحدة",
    "Oman": "سلطنة عمان",

    // Technical Sectors & Portfolio Tabs
    "Technical": "إدارة المشروعات",
    "Technical Portfolio": "محفظة إدارة المشروعات والمشروعات الفنية",
    "Governmental": "حكومي",
    "Educational": "تعليمي",
    "Commercial": "تجاري",
    "Residential": "سكني",
    "Year": "السنة",
    "All Years": "جميع السنوات",

    // Insights Page
    "INSIGHTS_TITLE": "الرؤى والأخبار",
    "Latest press releases, corporate updates, and architectural accolades": "أحدث البيانات الصحفية، التحديثات المؤسسية، والجوائز المعمارية",
    "ALL": "الكل",
    "NEWS": "الأخبار",
    "AWARDS": "الجوائز",
    "ARTICLES": "المقالات",

    // Project Details Page
    "Back to Portfolio": "العودة إلى المعرض",
    "Visual Presentation": "العرض المرئي",
    "Project Details": "تفاصيل المشروع",
    "Client": "العميل",
    "Status": "الحالة",
    "Ongoing": "قيد التنفيذ",
    "Completed": "مكتمل",
    "Tender": "طرح عطاء",
    "Design Stage": "مرحلة التصميم",
    "Concept Stage": "مرحلة الفكرة",

    // Locations / dynamic names
    "Muscat, Oman": "مسقط، عمان",
    "Riyadh, KSA": "الرياض، السعودية",
    "Cairo, Egypt": "القاهرة، مصر",
    "Saudi Arabia": "المملكة العربية السعودية",
    "Aswan, Egypt": "أسوان، مصر",
    "Hurghada, Red Sea, Egypt": "الغردقة، البحر الأحمر، مصر",

    // Project Titles
    "Zomra East": "زمرة إيست",
    "Saudi Korean Industrial Village (SKIV)": "القرية الصناعية السعودية الكورية",
    "Majarra Vision": "رؤية مجرة",
    "NEBU Commercial Mall": "مول نيبو التجاري",
    "Riviera Sahl Hasheesh": "ريفيرا سهل حشيش",
    "Sohob Residential District": "حي سحب السكني",
    "JuSuR Tourism Center": "مركز جسور السياحي",
    "Osuol Office Towers": "أبراج أصول المكتبية",
    "Lujain Resort Salalah": "منتجع لجين صلالة",
    "The Crystal Spark Tower": "برج كريستال سبارك",
    "The Spirit Tower": "برج الروح",
    "The Ring Tower": "برج الحلقة",
    "Tutera Pyramid Eco-City": "مدينة توتيرا الهرمية البيئية",
    "ANGELS OF MERCY": "ملائكة الرحمة",
    "Covid-19 Mobile Hospital": "مستشفى كوفيد-19 الميداني المتنقل",
    "TUTERA THE WALK": "توتيرا ذا ووك",
    "METATUT METAVERSE CITY": "مدينة ميتا توت الافتراضية",
    "Sun Of History": "شمس التاريخ",
    "king khufu avenue": "محور الملك خوفو",
    "The National Theater 2009-2014": "المسرح القومي 2009-2014",
    "TIMES SQUARE PROJECT": "مشروع تايمز سكوير",
    "Cairo 2050": "القاهرة 2050",
    "Giza 2030": "الجيزة 2030",
    "Sinai": "سيناء",
    "Luxor 2005-09": "الأقصر 2005-09",
    "EGYPT 712": "مصر 712",
    "The New Administrative Capital Cairo": "العاصمة الإدارية الجديدة القاهرة",
    "Vinhub data center, Camlam, Vietnam": "مركز بيانات فينهوب، كاملام، فيتنام",
    "SONGDO INTERNATIONAL CITY library, COMPETITION, korea": "مكتبة مدينة سونغدو الدولية، مسابقة، كوريا",
    "mada residence, OMAN": "سكن مدى، عمان",
    "PURA RESIDENCE": "سكن بورا",
    "Gaza vision": "رؤية غزة",
    "Adminstrative Tower, KSA": "البرج الإداري، السعودية",
    "ATLANTIS RESORT HURGHADA": "منتجع أتلانتس الغردقة",
    "ETOPIA RESIDENCE": "سكن إيتوبيا",
    "VORTEX RESORTS": "منتجعات فورتكس",
    "The Cloud, Abu Dhabi": "السحابة، أبو ظبي",
    "ENSAN City of Knowledge": "مدينة إنسان المعرفية",
    "Pearl Cave Tower, Oman": "برج كهف اللؤلؤ، عمان",
    "Grozny Competition, Russia": "مسابقة غروزني، روسيا",
    "LUNA CULTURAL CENTER, KSA": "مركز لونا الثقافي، السعودية",
    "Masirah-Island, OMAN": "جزيرة مصيرة، عمان",
    "WindRose International": "ويندروز الدولية",
    "Industrial Village, Jazan": "القرية الصناعية، جازان",
    "Damietta Governorate": "محافظة دمياط",
    "kemet tower": "برج كيميت",
    "TUT Lodge": "نزل توت",
    "The Crystal Pyramid": "الهرم الكريستالي",
    "Sahara International": "صحارى الدولية",
    "Family Health Center": "مركز صحة الأسرة",
    "Hurghada Marina": "مارينا الغردقة",
    "A'ARU 1.0 Space Colony": "مستعمرة الفضاء آرو 1.0",
    "UFO Space Tourism City": "مدينة يوفو لسياحة الفضاء",
    "Pearla Mall": "بيرلا مول",
    "The Entrance of Suez Canal": "مدخل قناة السويس",
    "The African Organization": "المنظمة الأفريقية",
    "NUT TOWER": "برج نوت",
    "MEDIA CITY": "مدينة الإعلام",
    "CUBE Portal": "بوابة كيو ب",
    "Sahara International School": "مدرسة الصحراء الدولية",
    "SKIV Saudi Korean Industrial Village": "القرية الصناعية السعودية الكورية",
    "Gaza calls غزة تنادى": "غزة تنادي",
    "Nebu Commercial Mall": "مول نيبو التجاري",
    "Virtual World & Metaverse Development": "تطوير العوالم الافتراضية والميتافيرس",
    "Tutera Digital Realm": "عالم توتيرا الرقمي",
    "Gaza, Palestine": "غزة، فلسطين",
    "New Administrative Capital, Cairo, Egypt": "العاصمة الإدارية الجديدة، القاهرة، مصر",
    "LRT & monorail terminal": "محطة القطار الخفيف والمنوريل",
    "CAIRO CAPITAL NEW TERMINAL": "محطة العاصمة القاهرة الجديدة",
    "Memorial Park Competition": "مسابقة حديقة التذكارية",
    "LUXOR NILE CRUISES MARINE": "مرسى بواخر النيل بالأقصر",
    "BELKAID MOSQUE": "مسجد بلقايد",
    "ATON HOTEL": "فندق آتون",
    "AMAZ Residence": "سكن أماز",
    "DIPLO RESIDENCE": "سكن ديبلو",
    "MIEDUM CITY": "مدينة ميدوم",
    "piano district": "منطقة البيانو",
    "Long Beach Resort": "منتجع لونج بيتش",
    "Faro Resort": "منتجع فارو",
    "KARNAK HOTEL & RESIDENCE": "فندق وسكن الكرنك",
    "El SHAMS CLUB": "نادي الشمس",
    "SEASPARK TWIN TOWERS": "أبراج سي سبارك التوأم",
    "BELLA MART MALL": "بيلا مارت مول",
    "BOARDWALK RESIDENCE": "سكن بوردووك",
    "BASHTEEL TRAIN STATION": "محطة قطار بشتيل",
    "Sokhna Logistics": "منطقة السخنة اللوجستية",
    "TRANSFORMATION MALL": "ترانسفورميشن مول",
    "The City Plaza": "ذا سيتي بلازا",
    "Mediterranean University": "جامعة البحر المتوسط",
    "The Green River": "النهر الأخضر",
    "Ras Eltin": "رأس التين",
    "The Oasis – The Capital Cairo": "الواحة - العاصمة القاهرة",
    "Central Business District": "منطقة الأعمال المركزية",
    "CITY OF KNOWLEDGE": "مدينة المعرفة",
    "57357 UNIVERSITY": "جامعة 57357",
    "JAZAN university, KSA": "جامعة جازان، السعودية",
    "The Atrium Food Court": "مجمع مطاعم الأتريوم",
    "Vortex Dubai Gateway": "بوابة فورتكس دبي",
    "Signature 5 Star Floating": "عائمة 5 نجوم مميزة",
    "AMWAJ TOWERS": "أبراج أمواج",
    "57357 SMART STUDIO": "استوديو 57357 الذكي",
    "Pedesterian bridges, KSA": "جسور المشاة، السعودية",
    "Palestinian Embassy": "السفارة الفلسطينية",
    "Mena Rainbow Square": "ميدان قوس قزح مينا",
    "AL AZHAR LIBRARY": "مكتبة الأزهر",
    "Contraco Headquarters, QATAR": "المقر الرئيسي لشركة كونتراكو، قطر",
    "ERAFRIKA, South Africa": "إيرافريكا، جنوب أفريقيا",
    "NABQ PROTECTED AREA": "محمية نبق",
    "Hout Bay Harbor, Finland": "مرفأ هوت باي، فنلندا",
    "Helsinki South Harbor, Finland": "مرفأ هلسنكي الجنوبي، فنلندا",
    "Al Fustat Open Museum": "متحف الفسطاط المفتوح",
    "Horus Island": "جزيرة حورس",
    "ESNA Historical Oasis": "واحة إسنا التاريخية",
    "Opera Gateway Competition": "مسابقة بوابة الأوبرا",
    "LUXOR CORNICHE": "كورنيش الأقصر",
    "Degla Safari Park": "حديقة دجلة لرحلات السفاري",
    "Maspiro Triangle": "مثلث ماسبيرو",

    // Project Locations
    "Fifth Settlement, New Cairo, Egypt": "التجمع الخامس، القاهرة الجديدة، مصر",
    "Jazan, Kingdom of Saudi Arabia (KSA)": "جازان، المملكة العربية السعودية",
    "Sahl Hasheesh, Hurghada, Egypt": "سهل حشيش، الغردقة، مصر",
    "Abu Dhabi, UAE": "أبو ظبي، الإمارات",
    "New Administrative Capital, Egypt": "العاصمة الإدارية الجديدة، مصر",
    "Sahl Hasheesh, Red Sea, Egypt": "سهل حشيش، البحر الأحمر، مصر",
    "Riyadh, Kingdom of Saudi Arabia (KSA)": "الرياض، المملكة العربية السعودية",
    "North Al-Seeb, Muscat, Oman": "شمال السيب، مسقط، عمان",
    "Al-Madinah Al-Munawwarah, KSA": "المدينة المنورة، السعودية",
    "Salalah, Oman": "صلالة، عمان",
    "Giza Plateau, Egypt": "هضبة الجيزة، مصر",
    "Giza, Egypt": "الجيزة، مصر",
    "Metaverse / Digital Space": "الميتافرس / الفضاء الرقمي",
    "New Cairo, Egypt": "القاهرة الجديدة، مصر",
    "Sinai Peninsula, Egypt": "شبه جزيرة سيناء، مصر",
    "Luxor, Egypt": "الأقصر، مصر",
    "Cam Lam, Vietnam": "كام لام، فيتنام",
    "Kingdom of Saudi Arabia (KSA)": "المملكة العربية السعودية",
    "Grozny, Russia": "غروزني، روسيا",
    "Doha, Qatar": "الدوحة، قطر",
    "Capetown, South Africa": "كيب تاون، جنوب أفريقيا",
    "Helsinki, Finland": "هلسنكي، فنلندا",

    // Insights titles
    "CUBE Consultants Signs Consultancy and Design Contract for Smouha Gate Project in Alexandria": "كيو ب للاستشارات توقع عقد استشارات وتصميم لمشروع بوابة سموحة بالإسكندرية",
    "CUBE Consultants Signs Strategic Memorandum of Understanding with Hunan Chamber of Commerce in Egypt to Strengthen Egyptian-Chinese Cooperation": "كيو ب للاستشارات توقع مذكرة تفاهم استراتيجية مع غرفة تجارة هونان بمصر لتعزيز التعاون المصري الصيني",
    "Opet Studios ( Tech Arm )": "أوبيت ستوديوز (الذراع التقني)",
    "Architecture Video Production & Storytelling: Why It Matters for Design Studios Today": "إنتاج فيديو العمارة ورواية القصص: لماذا يهم استوديوهات التصميم اليوم؟",
    "THE ARCHITECTURE OF ADMIN SPACES": "عمارة المساحات الإدارية",
    "Lujain Resort, Salalah: Designing a Water-Led Urban Ecosystem in Oman": "منتجع لجين، صلالة: تصميم نظام بيئي حضري مائي في عمان",
    "Digi-City: Saudi Arabia (2004)": "المدينة الرقمية: المملكة العربية السعودية (2004)",
    "Robotized Architecture: Automation & Kinetics": "العمارة الآلية: الأتمتة والحركة",
    "Form and Space Education in the New Millennium": "تعليم الشكل والفراغ في الألفية الجديدة",
    "Khufu Design Secrets: Ancient Geometry": "أسرار تصميم هرم خوفو: الهندسة القديمة",
    "Khufu Presentation Slides (Archcairo 2006)": "شرائح عرض خوفو (مؤتمر بنية القاهرة 2006)",
    "Games in Architectural Design Processes": "الألعاب في عمليات التصميم المعماري",
    "Digi-City Concept and Interactive Urbanism": "مفهوم المدينة الرقمية والعمران التفاعلي",
    "Robotized Architecture Presentation Slides": "شرائح عرض العمارة الآلية",
    "Cube partners with ITI": "كيو ب تتعاون مع معهد تكنولوجيا المعلومات ITI",
    "NEBU  Launch Event 2025": "حفل إطلاق نيبو 2025",
    "Entrepreneur: The METATUT: a Metaverse Inspired By King Tutankhamun": "ريادة الأعمال: ميتا توت: ميتافيرس مستوحى من الملك توت عنخ آمون",
    "Metaverse and Architecture": "الميتافيرس والهندسة المعمارية",
    "Projects under construction new capital - 2022": "مشاريع قيد الإنشاء في العاصمة الجديدة - 2022",
    "Cube wins 3 international awards during 2021-2022": "كيو ب تفوز بـ 3 جوائز دولية خلال 2021-2022",
    "Prof Dr. Ashraf Abdel Mohsen has been selected as Space Architecture Ambassador": "اختيار أ.د. أشرف عبد المحسن سفيراً لهندسة الفضاء",
    "Tutera | The Walk 10.08.21": "توتيرا | ذا ووك 10.08.21",
    "Bringing you a new definition to the digital magazine experience.": "نقدم لكم تعريفاً جديداً لتجربة المجلات الرقمية",
    "TUTERA PYRAMID": "هرم توتيرا",
    "The New Administrative Capital Award": "جائزة العاصمة الإدارية الجديدة",
    "Sahara International School Award": "جائزة مدرسة صحارى الدولية",
    "The Ancient Egyptian's Golden Parade": "موكب المومياوات الملكية الذهبي",
    "Join TUTERA": "انضم إلى توتيرا",
    "In CUBE, A new day means new beauty.": "في كيو ب، يوم جديد يعني جمالاً جديداً",
    "TUTERA": "توتيرا",
    "Top 15 Architectural Studios in Egypt": "أفضل 15 استوديو معماري في مصر",
    "Egypt wants everything top notch in new capital city": "مصر تريد كل شيء على أعلى مستوى في العاصمة الجديدة",
    "INVEST GATE COVERING CUBE CONSULTANTS EFFORT TOWARDS REALIZING THE QUALITY OF LIFE": "إنفست جيت تغطي جهود كيو ب للاستشارات نحو تحقيق جودة الحياة",
    "5+UDC. The Experts Reunion 2015": "5+UDC. اجتماع الخبراء 2015",
    "The Ring Tower 2015": "برج الحلقة 2015",
    "The Crystal Spark Tower 2015": "برج كريستال سبارك 2015",
    "The Spirit Tower 2013": "برج الروح 2013",
    "ROBOTIZED ARCHITECTURE VISION": "رؤية العمارة الآلية",
    "Rethinking The Future Awards 2021 - First Award": "جوائز إعادة التفكير في المستقبل 2021 - الجائزة الأولى",
    "Rethinking The Future Awards 2021 - Second Award": "جوائز إعادة التفكير في المستقبل 2021 - الجائزة الثانية",
    "Rethinking The Future Awards 2021 - Third Award": "جوائز إعادة التفكير في المستقبل 2021 - الجائزة الثالثة",
    "Global Future Design Awards 2022 - Gold Winner": "جوائز التصميم المستقبلي العالمي 2022 - الفائز الذهبي",
    "Space Village Design Competition 2022 - First Award": "مسابقة تصميم قرية الفضاء 2022 - الجائزة الأولى",
    "World Design Awards 2023 - Winner": "جوائز التصميم العالمية 2023 - الفائز",
    "Egypt Retail Summit 2021 - Excellence Award": "قمة التجزئة المصرية 2021 - جائزة التميز",
    "Space Architecture Ambassador Appointment": "تعيين سفير عمارة الفضاء"
  }
};

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const savedLang = localStorage.getItem("lang") as Language;
      if (savedLang === "en" || savedLang === "ar") {
        return savedLang;
      }
    }
    return "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("lang", lang);
  };

  const dir = language === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    // Dynamically apply body layout direction
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [dir, language]);

  const t = (key: string): string => {
    if (language === "ar") {
      return translations.ar[key] || key;
    }
    return translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
